# Generated by Django 5.1.4 on 2025-01-15 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0004_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_add_book', 'Can-add-book'), ('can_change_book', 'Can-change-book'), ('can_delete_book', 'Can-delete-book')]},
        ),
    ]
