# Generated by Django 5.1.4 on 2025-01-15 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0006_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_add_custom_book', 'Can add custom book'), ('can_change_custom_book', 'Can change custom book'), ('can_delete_custom_book', 'Can delete custom book')]},
        ),
    ]
